### ISSUE TITLE
error in netgsa.Rmd

### ISSUE THREAD

**Issue by ghost** [drjingma/netgsa#1]
Dear Dr Ma

was trying to run the netgsa.Rmd and it ran into an error

```
for (k in 1:ncond){
  data_c <- sx[,(group==k)]
  # select the tuning parameter
  fitBIC <- bic.netEst.undir(data_c,one=sout$Adj,
                             lambda=seq(1,10)*sqrt(log(p)/ncol(data_c)),eta=0.1)
  # refit the network
  fit <- netEst.undir(data_c,one=sout$Adj,
                      lambda=which.min(fitBIC$BIC)*sqrt(log(p)/ncol(data_c)),eta=0.1)
  Amat[[k]] <- fit$Adj
}
Error in matTr(empcov %*% siginv) : 
  argument "b" is missing, with no default
```

should the following line in bic.netEst.undir.R:
```
bic.score[loop.lambda, loop.w] = matTr(empcov %*% siginv) - determinant(siginv, logarithm = T)$modulus + log(n) * no.edge/(2 * n)
```
be matTr(empcov, siginv) instead?

Thank you.

**Comment by drjingma** [comment]
Hello, apologies for getting back late. 

Yes, you've got it! It should be comma instead of the matrix product sign. The above error was due to an incomplete update to the function matTr and a few other features. I have now updated all the functions. The github version compiles without a problem for me. Hopefully it will work for you too! 

Thanks for pointing this out!

**Comment by ghost** [comment]
Hi Prof Ma, would netgsa work with differential data, i.e. log2fc changes? Thank you

**Comment by drjingma** [comment]
Hello, netgsa currently does not work for differential data. We are working on adding this feature to future releases. Stay tuned!
